---
title: "2021_LB_Forum"
author: "Naeem Chowdhury"
date: "3/1/2021"
output: html_document
---

# Setup

## Set Directories
```{r}
home <- getwd()
data.dir <- file.path(home, "data")
output.dir <- file.path(home, "output")
```

## Load Packages and fonts
```{r}
# install.packages('tidyverse')
library(tidyverse)
# install.packages('plotly')
library(plotly)
#install.packages('extrafont')
library(extrafont)
#install.packages('RColorBrewer')
library(RColorBrewer)
#install.packages('waffle')
library(waffle)
#font_import()
#loadfonts(device="win") 
```


## Data Read-in
```{r}
cls.color <- rgb(57, 164,184, max = 255)


legacy.df <- read_csv(file.path(data.dir, 'old_members.csv')) %>% 
  slice_head(n = 322)
fresh.df <- read_csv(file.path(data.dir, '2019-2021_members.csv'))
```

# Analysis

## Side-by-Side Bar Plot

### Data restructuring

```{r}
# Issue 1: Remove repeated members
# RESOLVED Issue 2: Pull all language rows, removing NAs and repeated languages for a single person
# RESOLVED Issue 3: stack resulting language rows
# RESOLVED Issue 4: Group_by summarize count

lang.old.1 <- legacy.df %>% 
  select(`What CLS Language did you study?`) %>% 
  drop_na() %>% 
  rename(Language = `What CLS Language did you study?`)

lang.old.2 <- legacy.df %>%
  filter(`What CLS Language did you study?` != `What CLS Language did you study?_1`) %>% 
  select(`What CLS Language did you study?_1`) %>% 
  drop_na() %>% 
  rename(Language = `What CLS Language did you study?_1`)

lang.new.1 <- fresh.df %>% 
  select(`What CLS Language did you study?`) %>% 
  drop_na() %>% 
  rename(Language = `What CLS Language did you study?`)

lang.new.2 <- fresh.df %>% 
  filter(`What CLS Language did you study?` != `What CLS Language did you study?_1`) %>% 
  select(`What CLS Language did you study?_1`) %>% 
  drop_na() %>% 
  rename(Language = `What CLS Language did you study?_1`)


lang.all <- lang.old.1 %>% 
  add_row(lang.old.2) %>% 
  add_row(lang.new.1) %>% 
  mutate(n = 1)

lang.count <- lang.all %>% 
  group_by(Language) %>% 
  summarise(count = sum(n)) %>% 
  mutate(Language = fct_reorder(Language, count))
```

### Bar Plot
```{r}
fig <- lang.count %>% ggplot(aes(x = Language, y =count)) +
  geom_bar(aes(),
           fill = cls.color,
           position = position_dodge(width = 1), 
           stat = "identity") +
  labs(title = "CLSAS Language Participation",
       subtitle = "How many CLSAS members studied each critical language?") +
  ylab("Number of members") +
  xlab("") +
  scale_y_continuous(breaks = seq(0,130,10)) +
  coord_flip() + 
  theme_minimal() +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(size = 24, face = 'bold'),
        plot.subtitle = element_text(size = 16, face = 'italic'),
        text = element_text(family = "Yu Mincho Demibold"),
        legend.position = "none")


fig

fig2 <- lang.count %>% ggplot(aes(x = Language, y =count)) +
  geom_bar(aes(),
           fill = cls.color,
           position = position_dodge(width = 1), 
           stat = "identity") +
  labs(title = "CLSAS Language Participation",
       subtitle = "How many CLSAS members studied each critical language?") +
  geom_text(aes(label=count), position=position_dodge(width=0.9), hjust=0) +
  ylab("Number of members") +
  xlab("") +
  scale_y_continuous(breaks = seq(0,130,10)) +
  coord_flip() + 
  theme_minimal() +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        plot.title = element_text(size = 24, face = 'bold'),
        plot.subtitle = element_text(size = 16, face = 'italic'),
        text = element_text(family = "Yu Mincho Demibold"),
        legend.position = "none")
  
fig2
```

### Piechart (Scrapped)
```{r}
lang.count.alpha <- lang.all %>% 
  group_by(Language) %>% 
  summarise(count = sum(n))

fig3 <- lang.count.alpha %>% 
  ggplot(aes(x="", y=count, fill=Language)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void()

fig3

```

### Waffle Chart
```{r}

```

